### ISSUE TITLE
user friendliness issue on Windows XP SP3 (Warning missing)

### ISSUE THREAD

**Issue by pfluegl** [seancolyer/gmail-crypt#10]
I tested this on v14 (from today) on Ubuntu 12.04 and Windows XP SP3. There is no functional problem, just a minor user-friendliness issue.

There is NO issue on Ubuntu 12.04. The issue is ONLY on the Windows XP platform. 

On Windows XP: I create a new email/msg. I leave the passwd field empty. I click the "encrypt with signature" or "sign only" button from the pulldown menu. NOTHING happens. No warning is displayed, nothing is encrypted or signed. 

On Ubuntu it works as desired: I click the "encrypt with signature" or "sign only" button from the pulldown menu and correctly as a response I get the warning text "Mymail-Crypt for Gmail was unable to read your key. Is your password correct?" This warning is missing in XP.

**Comment by seancolyer** [comment]
Warnings have been made much more visible since this ticket was originally written.

If this is still an issue, please re-open.
