### ISSUE TITLE
Import keys

### ISSUE THREAD

**Issue by Abouelzelouf** [seancolyer/gmail-crypt#13]
I am not able import my private key created using gpg4win?
I got this message:
Mymail-Crypt for Gmail was unable to read your key. It would be great if you could contact us so we can help figure out what went wrong.
is there any solution for this?

Regards

**Comment by tomachinz** [comment]
Doesn't work for me either. Clean install, never used OpenPGP, running in Chrome Version 48.0.2564.109 (64-bit) on Mac os 10.10.5 (14F1605).

Installed the Chrome Extensions, generated a fresh key,  rebooted, loaded gmail.com, click Compose, Sign, and get 

**Mymail-Crypt For Gmail was unable to read your key. Is your password correct?**
