### ISSUE TITLE
8192 bit key causes SHA1 to be used when signing

### ISSUE THREAD

**Issue by harisbinali** [seancolyer/gmail-crypt#27]
Hi, I use a 8192 bit RSA key and when I sign emails Mymail-Crypt seems to ignore the prefs in my key and sign in SHA1

I am not quite sure but I also think something similar is happening when I encrypt messages, preferences ignored and 3DES is used.

Any ideas what's causing this?

**Comment by seancolyer** [comment]
Closing this, all OpenPGP.js versions now (and have for a long time) default to SHA256
