### ISSUE TITLE
double message on decrypt

### ISSUE THREAD

**Issue by dbgdngit** [seancolyer/gmail-crypt#40]
Hi
When i decrypt a message the content gets repeated twice; regardless of sender
Same for my colleagues when i encrypt and send to them
mymail crypt version 24
Chrome Version 28.0.1500.95

**Comment by seancolyer** [comment]
I am closing this because the way the decrypt works has fundamentally changed since then and I have had no other reports of this issue.

If it is still occurring, please re-open.
