### ISSUE TITLE
Can't sign outgoing message: "Unable to find a private key ..."

### ISSUE THREAD

**Issue by alenkei** [seancolyer/gmail-crypt#61]
Hi,

Thank you for a very useful extension.

I have an issue with signing outgoing emails:
"Unable to find a private key for the given user. Have you inserted yours in the Options page?"

I originally created my key pair for  my yahoo.com email address and I am now using my lenkei.com account.  I have uploaded my yahoo.com key pair via the Options page.

I guess that gmail-crypt doesn't use the yahoo.com private key because I'm sending from my lenkei.com address. 

Can we have an option to tell it to use a particular private key for signing?

Best regards,
Andrei

**Comment by suhasbhairav** [comment]
Has this issue been fixed yet? I'm still getting the same error.
