### ISSUE TITLE
Mymail-Crypt does not fail to verify signature when it should.

### ISSUE THREAD

**Issue by Borgrimm** [seancolyer/gmail-crypt#70]
When a message is signed but altered after signing mymail-crypt will verify the signature without trouble. Where instead it should fail to verify because of the changed content.

Running mymail-crypt 32 from chrome store on Google Chrome 41.0.2272.89 (64-bit) in both Linux and 
Windows.

**Comment by seancolyer** [comment]
I just pushed a fix for this to github and the chrome web store, releasing version 33.
